/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CFlex: typeof import('./src/components/flex/CFlex.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    FileCard: typeof import('./src/components/file_loader/FileCard.vue')['default']
    FileCardSet: typeof import('./src/components/file_loader/FileCardSet.vue')['default']
    FileLoader: typeof import('./src/components/file_loader/FileLoader.vue')['default']
    HFlex: typeof import('./src/components/flex/HFlex.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPanel: typeof import('primevue/scrollpanel')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('primevue/tag')['default']
    Titlebar: typeof import('./src/components/Titlebar.vue')['default']
    VFlex: typeof import('./src/components/flex/VFlex.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
